name: CI
on: [push] # Se lance dès que tu envoies du code
jobs:
  hello-job:
    runs-on: ubuntu-latest # Le robot utilise un ordinateur Linux
    steps:
      - name: Say Hello
        run: echo "Hello pipelines' world !"

      